[supabase]
url = "https://lnfthmygvljwxbudvpvx.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxuZnRobXlndmxqd3hidWR2cHZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc3NDc2NTIsImV4cCI6MjA5MzMyMzY1Mn0.SMi3WgJj95dohg_qWmuNBdYcDZI-Qv2kYYSpHQDTqOQ"
